<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.179" timestamp="2023-05-16T12:39:19.265810" hostname="Mustafas-MBP.attlocal.net"><testcase classname="test_multiplication" name="test_multiplication[1-11]" time="0.002" /><testcase classname="test_multiplication" name="test_multiplication[2-22]" time="0.001" /><testcase classname="test_multiplication" name="test_multiplication[3-35]" time="0.002"><failure message="assert (11 * 3) == 35">num = 3, output = 35

    @pytest.mark.parametrize("num, output",[(1,11),(2,22),(3,35),(4,44)])
    def test_multiplication(num, output):
&gt;       assert 11 * (num) == output
E       assert (11 * 3) == 35

test_multiplication.py:5: AssertionError</failure></testcase><testcase classname="test_multiplication" name="test_multiplication[4-44]" time="0.002" /></testsuite></testsuites>